# Generated by Django 5.1.15 on 2026-03-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('customer', 'Customer'), ('annotator', 'Annotator')], default='user', max_length=32),
        ),
    ]
