# Generated by Django 5.1.15 on 2026-04-16 11:44

import apps.users.models
from django.db import migrations, models


def migrate_legacy_user_fields(apps, schema_editor):
    User = apps.get_model("users", "User")
    seen_emails: set[str] = set()

    for user in User.objects.all().order_by("id"):
        raw_email = (user.email or "").strip().lower()
        email = raw_email
        if not email or email in seen_emails:
            email = f"legacy-user-{user.id}@local.invalid"

        full_name_parts = [
            (getattr(user, "first_name", "") or "").strip(),
            (getattr(user, "last_name", "") or "").strip(),
        ]
        full_name = " ".join(part for part in full_name_parts if part)
        if not full_name:
            full_name = (getattr(user, "username", "") or "").strip() or email

        user.email = email
        user.full_name = full_name
        user.save(update_fields=["email", "full_name"])
        seen_emails.add(email)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(migrate_legacy_user_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
