from django.urls import path

from apps.labeling.api.v1.views import (
    FrameTaskAnnotationView,
    FrameTaskDetailView,
    FrameTaskListView,
    RoomNextTaskView,
    RoomReviewTaskListView,
    RoomSubmittedTaskListView,
    VideoDetailView,
    VideoFrameAnnotationExportView,
    VideoFrameView,
    VideoGenerateFrameTasksView,
    VideoSelectionGenerateFrameTasksView,
    VideoSelectionDetailView,
    VideoSelectionListCreateView,
    TaskRejectView,
    TaskReturnForRevisionView,
    TaskMySubmissionView,
    TaskReviewDetailView,
    TaskSkipView,
    TaskSubmitView,
    TaskValidationVoteView,
)


urlpatterns = [
    path("rooms/<int:room_id>/tasks/next/", RoomNextTaskView.as_view(), name="room-next-task"),
    path("rooms/<int:room_id>/tasks/submitted/mine/", RoomSubmittedTaskListView.as_view(), name="room-submitted-mine"),
    path("rooms/<int:room_id>/review/tasks/", RoomReviewTaskListView.as_view(), name="room-review-tasks"),
    path("tasks/<int:task_id>/skip/", TaskSkipView.as_view(), name="task-skip"),
    path("tasks/<int:task_id>/submit/", TaskSubmitView.as_view(), name="task-submit"),
    path("tasks/<int:task_id>/my-submission/", TaskMySubmissionView.as_view(), name="task-my-submission"),
    path("tasks/<int:task_id>/review/", TaskReviewDetailView.as_view(), name="task-review-detail"),
    path("tasks/<int:task_id>/validation-vote/", TaskValidationVoteView.as_view(), name="task-validation-vote"),
    path("tasks/<int:task_id>/reject/", TaskRejectView.as_view(), name="task-reject"),
    path("tasks/<int:task_id>/return-for-revision/", TaskReturnForRevisionView.as_view(), name="task-return-for-revision"),
    path("videos/<int:video_id>/", VideoDetailView.as_view(), name="video-detail"),
    path("videos/<int:video_id>/selections/", VideoSelectionListCreateView.as_view(), name="video-selection-list-create"),
    path("video-selections/<int:selection_id>/", VideoSelectionDetailView.as_view(), name="video-selection-detail"),
    path(
        "video-selections/<int:selection_id>/generate-frame-tasks/",
        VideoSelectionGenerateFrameTasksView.as_view(),
        name="video-selection-generate-frame-tasks",
    ),
    path("videos/<int:video_id>/generate-frame-tasks/", VideoGenerateFrameTasksView.as_view(), name="video-generate-frame-tasks"),
    path("frame-tasks/", FrameTaskListView.as_view(), name="frame-task-list"),
    path("frame-tasks/<int:task_id>/", FrameTaskDetailView.as_view(), name="frame-task-detail"),
    path("videos/<int:video_id>/frames/<int:frame_index>/", VideoFrameView.as_view(), name="video-frame-detail"),
    path("frame-tasks/<int:task_id>/annotation/", FrameTaskAnnotationView.as_view(), name="frame-task-annotation"),
    path("videos/<int:video_id>/export/", VideoFrameAnnotationExportView.as_view(), name="video-frame-annotation-export"),
]
