# Generated by Django 5.1.15 on 2026-04-21 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0004_task_workflow_stage_and_parent_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='annotation',
            name='unique_task_annotator_annotation',
        ),
        migrations.RemoveConstraint(
            model_name='taskassignment',
            name='unique_task_assignment_annotator',
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(fields=('task', 'annotator', 'round_number'), name='unique_task_assignment_round_annotator'),
        ),
    ]
