# Generated by Django 5.1.15 on 2026-05-08 08:05

import apps.labeling.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0007_task_in_review_validationvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_frame', models.PositiveIntegerField()),
                ('end_frame', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('generated', 'Generated')], default='active', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_selections', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_selections', to='labeling.task')),
            ],
            options={
                'ordering': ('start_frame', 'end_frame', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FrameAnnotationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frame_index', models.PositiveIntegerField()),
                ('time_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('skipped', 'Skipped'), ('uncertain', 'Uncertain')], default='pending', max_length=16)),
                ('frame_image', models.FileField(blank=True, upload_to=apps.labeling.models.frame_source_upload_to)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_annotation_tasks', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_annotation_tasks', to='labeling.task')),
                ('source_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_tasks', to='labeling.videoselection')),
            ],
            options={
                'ordering': ('video_id', 'frame_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FrameAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frame_index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('annotated', 'Annotated'), ('empty', 'Empty'), ('uncertain', 'Uncertain')], max_length=16)),
                ('objects_payload', models.JSONField(db_column='objects', default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_annotations', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_annotations', to='labeling.task')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='labeling.frameannotationtask')),
            ],
            options={
                'ordering': ('video_id', 'frame_index', 'id'),
                'indexes': [models.Index(fields=['video', 'status'], name='labeling_fa_video_s_d56b4d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='videoselection',
            index=models.Index(fields=['video', 'status'], name='labeling_vs_video_s_2d969e_idx'),
        ),
        migrations.AddIndex(
            model_name='frameannotationtask',
            index=models.Index(fields=['video', 'status'], name='labeling_fat_video__0d6ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='frameannotationtask',
            index=models.Index(fields=['assigned_to', 'status'], name='labeling_fat_assign_ef78dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='frameannotationtask',
            constraint=models.UniqueConstraint(fields=('video', 'frame_index'), name='unique_video_frame_annotation_task'),
        ),
    ]
