# Generated by Django 5.1.15 on 2026-05-12 11:21

import apps.labeling.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0007_task_in_review_validationvote'),
        ('rooms', '0014_room_review_voting_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(upload_to=apps.labeling.models.video_asset_upload_to)),
                ('source_name', models.CharField(max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('source_frame_rate', models.PositiveIntegerField(default=25)),
                ('extraction_fps', models.PositiveIntegerField(blank=True, null=True)),
                ('frame_step', models.PositiveIntegerField(default=1)),
                ('max_frames', models.PositiveIntegerField(default=1000)),
                ('manual_keyframe_percent', models.PositiveSmallIntegerField(default=10)),
                ('auto_default_assignment_quota', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('extraction_job_id', models.CharField(blank=True, max_length=255)),
                ('interpolation_job_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_assets', to='rooms.room')),
            ],
            options={
                'ordering': ('room_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frame_number', models.PositiveIntegerField()),
                ('timestamp', models.FloatField(default=0)),
                ('role', models.CharField(choices=[('manual_keyframe', 'Manual keyframe'), ('interpolation_target', 'Interpolation target')], default='interpolation_target', max_length=32)),
                ('state', models.CharField(choices=[('waiting_interpolation', 'Waiting interpolation'), ('pending_manual', 'Pending manual'), ('manual_submitted', 'Manual submitted'), ('no_object', 'No object'), ('generated_review', 'Generated review'), ('generated_accepted', 'Generated accepted'), ('generated_rejected', 'Generated rejected')], default='pending_manual', max_length=32)),
                ('generated_payload', models.JSONField(blank=True, null=True)),
                ('generated_from_frames', models.JSONField(blank=True, default=list)),
                ('trajectory_warnings', models.JSONField(blank=True, default=list)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_frame', to='labeling.task')),
                ('video_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='labeling.videoasset')),
            ],
            options={
                'ordering': ('video_asset_id', 'frame_number', 'id'),
                'constraints': [models.UniqueConstraint(fields=('video_asset', 'frame_number'), name='unique_video_asset_frame_number')],
            },
        ),
    ]
