# Generated by Django 5.1.15 on 2026-05-11 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0008_videoselection_frameannotationtask_frameannotation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameannotation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='labeling.frameannotationtask'),
        ),
        migrations.AddConstraint(
            model_name='frameannotation',
            constraint=models.UniqueConstraint(fields=('task', 'created_by'), name='unique_frame_annotation_task_user'),
        ),
    ]
