# Generated by Django 5.1.15 on 2026-04-16 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_room_invite_tokens(apps, schema_editor):
    Room = apps.get_model("rooms", "Room")
    for room in Room.objects.filter(invite_token__isnull=True).order_by("id"):
        room.invite_token = uuid.uuid4()
        room.save(update_fields=["invite_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_roommembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invite_token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name='RoomJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_room_join_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_room_join_request')],
            },
        ),
        migrations.RunPython(populate_room_invite_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='room',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
