# Generated by Codex on 2026-04-25

from django.db import migrations, models


def backfill_default_assignment_quota(apps, schema_editor):
    Room = apps.get_model("rooms", "Room")
    Task = apps.get_model("labeling", "Task")

    for room in Room.objects.all().only("id"):
        primary_task_count = Task.objects.filter(room_id=room.id, parent_task_id__isnull=True).count()
        Room.objects.filter(id=room.id).update(default_assignment_quota=primary_task_count)


class Migration(migrations.Migration):

    dependencies = [
        ("labeling", "0006_alter_taskassignment_status"),
        ("rooms", "0012_roomassignmentquota"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="default_assignment_quota",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_default_assignment_quota, migrations.RunPython.noop),
    ]
